Project Airbnb {
	database_type: 'PostgreSQL'
	note: '''
		# Airbnb Sample Database
	'''
}

Ref: cities.country_id > contries.id
Ref: places.host_id > hosts.id
Ref: users.id < bookings.user_id
Ref: bookings.place_id > places.id
Ref: places.city_id > cities.id
Ref: hosts.user_id > users.id
Ref: "bookings"."id" < "reviews". "booking_id"

Table users {
	id integer [pk]
	email varchar [unique, note: "Used as login id"]
}

Table bookings {
	id integer [pk]
	user_id integer
	place_id integer
	start_date date
	end_date date
	price_per_night float
	num_nights integer

	note: "Some notes about bookings"
}
