module.exports = [
  {
    id: 1,
    name: 'Promise686',
    settings: {
      meta_title: 'Promise Serves',
      meta_desc: 'Volunteer Coordination System for Promise 686',
      color_primary: '#ABAC22',
      color_secondary: '#1F1D18',
      color_set_navbar: 'white-black',
      color_primary_text: '#fff',
      color_primary_contrast: 'offset',
      color_primary_offset: '#797a00',
      color_secondary_text: '#000',
      color_secondary_contrast: '',
      color_secondary_offset: '#514f4a',
    },
    status: 40,
    subdomain: null,
  },
  {
    id: 4,
    name: 'Welcomed',
    settings: {
      meta_title: 'Welcomed - Volunteer Coordination System',
      meta_desc: '',
      color_primary: '#000000',
      color_secondary: '#C59D5F',
      color_set_navbar: 'black-white',
      color_primary_text: '#000',
      color_primary_contrast: '',
      color_primary_offset: '#323232',
      color_secondary_text: '#fff',
      color_secondary_contrast: 'offset',
      color_secondary_offset: '#936b2d',
    },
    status: 40,
    subdomain: 'welcomed',
  },
  {
    id: 5,
    name: 'Hands of Hope',
    settings: {
      meta_title: 'Hands of Hope - Volunteer Coordination System',
      meta_desc: '',
      color_primary: '#231F20',
      color_secondary: '#77C6DA',
      color_set_navbar: 'white-black',
      color_primary_text: '#000',
      color_primary_contrast: '',
      color_primary_offset: '#555152',
      color_secondary_text: '#fff',
      color_secondary_contrast: 'offset',
      color_secondary_offset: '#4594a8',
    },
    status: 40,
    subdomain: 'handsofhope',
  },
  {
    id: 6,
    name: 'Restoration Rome',
    settings: {
      meta_title: 'Restoration Rome - Volunteer Coordination System',
      meta_desc: '',
      color_primary: '#25AFDA',
      color_secondary: '#FEE032',
      color_set_navbar: 'white-black',
      color_primary_text: '#fff',
      color_primary_contrast: 'offset',
      color_primary_offset: '#007da8',
      color_secondary_text: '#fff',
      color_secondary_contrast: 'offset',
      color_secondary_offset: '#ccae00',
    },
    status: 40,
    subdomain: 'restorationrome',
  },
  {
    id: 7,
    name: 'Florida1.27',
    settings: {
      meta_title: 'Florida1.27 - Volunteer Coordination System',
      meta_desc: '',
      color_primary: '#87C139',
      color_secondary: '#014E96',
      color_set_navbar: 'white-black',
      color_primary_text: '#fff',
      color_primary_contrast: 'offset',
      color_primary_offset: '#558f07',
      color_secondary_text: '#000',
      color_secondary_contrast: '',
      color_secondary_offset: '#3380c8',
    },
    status: 40,
    subdomain: 'florida127',
  },
  {
    id: 8,
    name: 'Clement Arts',
    settings: {
      meta_title: 'Clement Arts - Volunteer Coordination System',
      meta_desc: '',
      color_primary: '#999999',
      color_secondary: '#5098FB',
      color_set_navbar: 'white-black',
      color_primary_text: '#fff',
      color_primary_contrast: 'offset',
      color_primary_offset: '#676767',
      color_secondary_text: '#fff',
      color_secondary_contrast: 'offset',
      color_secondary_offset: '#1e66c9',
    },
    status: 40,
    subdomain: 'clementarts',
  },
  {
    id: 9,
    name: 'Chosen For Life',
    settings: {
      meta_title: 'Chosen For Life - Volunteer Coordination System',
      meta_desc: '',
      color_primary: '#95BA3D',
      color_secondary: '#5D482F',
      color_set_navbar: 'white-black',
      color_primary_text: '#fff',
      color_primary_contrast: 'offset',
      color_primary_offset: '#63880b',
      color_secondary_text: '#000',
      color_secondary_contrast: '',
      color_secondary_offset: '#8f7a61',
    },
    status: 40,
    subdomain: 'chosenforlifeministries',
  },
  {
    id: 10,
    name: 'Fostering Family Ministries Inc.',
    settings: null,
    status: -4,
    subdomain: 'fosteringfamilyministries',
  },
  {
    id: 12,
    name: 'Fostering the Family',
    settings: {
      meta_title: 'fosteringthefamily,org',
      meta_desc: 'Foster care support',
      color_primary: '#2C246D',
      color_secondary: '#0C8E36',
      color_set_navbar: 'white-black',
      color_primary_text: '#000',
      color_primary_contrast: '',
      color_primary_offset: '#5e569f',
      color_secondary_text: '#000',
      color_secondary_contrast: '',
      color_secondary_offset: '#3ec068',
    },
    status: 40,
    subdomain: 'fosteringthefamily',
  },
  {
    id: 13,
    name: 'Starfish Ministry',
    settings: {
      meta_title: 'Hillside Community Church - Volunteer Coordination System',
      meta_desc: '',
      color_primary: '#DA5F23',
      color_secondary: '#292728',
      color_set_navbar: 'white-black',
      color_primary_text: '#000',
      color_primary_contrast: '',
      color_primary_offset: '#ff9155',
      color_secondary_text: '#000',
      color_secondary_contrast: '',
      color_secondary_offset: '#5b595a',
    },
    status: 40,
    subdomain: 'starfish',
  },
  {
    id: 14,
    name: 'Olive Crest Family Care',
    settings: {
      meta_title: 'Olive Crest Foster Care - Volunteer Coordination System',
      meta_desc: '',
      color_primary: '#8B9A3B',
      color_secondary: '#5D482F',
      color_set_navbar: 'black-white',
      color_primary_text: '#fff',
      color_primary_contrast: 'offset',
      color_primary_offset: '#596809',
      color_secondary_text: '#000',
      color_secondary_contrast: '',
      color_secondary_offset: '#8f7a61',
    },
    status: 40,
    subdomain: 'olivecrest',
  },
  {
    id: 15,
    name: 'Kansas City Gracepoint',
    settings: {
      meta_title: 'Kansas City Gracepoint - Volunteer Coordination System',
      meta_desc: '',
      color_primary: '#D92129',
      color_secondary: '#C7C7C7',
      color_set_navbar: 'black-white',
      color_primary_text: '#000',
      color_primary_contrast: '',
      color_primary_offset: '#ff535b',
      color_secondary_text: '#fff',
      color_secondary_contrast: 'offset',
      color_secondary_offset: '#959595',
    },
    status: 40,
    subdomain: 'kcgracepoint',
  },
  {
    id: 16,
    name: '4KIDS',
    settings: {
      meta_title: '4KIDS of South  Florida - Volunteer Coordination System',
      meta_desc: '',
      color_primary: '#1897DF',
      color_secondary: '#000000',
      color_set_navbar: 'white-black',
      color_primary_text: '#fff',
      color_primary_contrast: 'offset',
      color_primary_offset: '#0065ad',
      color_secondary_text: '#000',
      color_secondary_contrast: '',
      color_secondary_offset: '#323232',
    },
    status: 40,
    subdomain: '4kids',
  },
  {
    id: 17,
    name: 'Grace Fellowship',
    settings: null,
    status: 40,
    subdomain: 'gracefellowship',
  },
  {
    id: 18,
    name: 'Fostering Joy',
    settings: {
      meta_title: 'Fostering Joy - Volunteer Coordination System',
      meta_desc: '',
      color_primary: '#97C93E',
      color_secondary: '#17414E',
      color_set_navbar: 'white-black',
      color_primary_text: '#fff',
      color_primary_contrast: 'offset',
      color_primary_offset: '#65970c',
      color_secondary_text: '#000',
      color_secondary_contrast: '',
      color_secondary_offset: '#497380',
    },
    status: 40,
    subdomain: 'fosteringjoy',
  },
  {
    id: 19,
    name: 'Hope Community Church',
    settings: null,
    status: 10,
    subdomain: 'hopecc',
  },
  {
    id: 20,
    name: 'Commission 127',
    settings: {
      meta_title: 'Commission 127 - Volunteer Coordination System',
      meta_desc: '',
      color_primary: '#00A59B',
      color_secondary: '#58585A',
      color_set_navbar: 'white-black',
      color_primary_text: '#000',
      color_primary_contrast: '',
      color_primary_offset: '#32d7cd',
      color_secondary_text: '#000',
      color_secondary_contrast: '',
      color_secondary_offset: '#8a8a8c',
    },
    status: 40,
    subdomain: 'c127',
  },
  {
    id: 21,
    name: 'Every Church Every Child',
    settings: {
      meta_title: 'Every Church Every Child - Volunteer Coordination System',
      meta_desc: '',
      color_primary: '#000000',
      color_secondary: '#878787',
      color_set_navbar: 'white-black',
      color_primary_text: '#000',
      color_primary_contrast: '',
      color_primary_offset: '#323232',
      color_secondary_text: '#fff',
      color_secondary_contrast: 'offset',
      color_secondary_offset: '#555555',
    },
    status: 40,
    subdomain: 'ecec',
  },
  {
    id: 22,
    name: 'Wellroot Family Services',
    settings: {
      meta_title: 'Wellroot Family Services',
      meta_desc: '',
      color_primary: '#6960B9',
      color_secondary: '#36BC8E',
      color_set_navbar: 'white-black',
      color_primary_text: '#fff',
      color_primary_contrast: 'offset',
      color_primary_offset: '#372e87',
      color_secondary_text: '#fff',
      color_secondary_contrast: 'offset',
      color_secondary_offset: '#048a5c',
    },
    status: 40,
    subdomain: 'wellroot',
  },
  {
    id: 24,
    name: 'Agape of Central Alabama',
    settings: {
      meta_title: 'Agape - Volunteer Coordination System',
      meta_desc: '',
      color_primary: '#70D1E0',
      color_secondary: '#000000',
      color_set_navbar: 'white-black',
      color_primary_text: '#fff',
      color_primary_contrast: 'offset',
      color_primary_offset: '#3e9fae',
      color_secondary_text: '#000',
      color_secondary_contrast: '',
      color_secondary_offset: '#323232',
    },
    status: 40,
    subdomain: 'agape',
  },
  {
    id: 25,
    name: 'Hope 1312 Collective',
    settings: {
      meta_title: 'Hope 1312 Collective - Volunteer Coordination System',
      meta_desc: '',
      color_primary: '#EB4B5C',
      color_secondary: '#5EA8A7',
      color_set_navbar: 'white-black',
      color_primary_text: '#fff',
      color_primary_contrast: 'offset',
      color_primary_offset: '#b9192a',
      color_secondary_text: '#fff',
      color_secondary_contrast: 'offset',
      color_secondary_offset: '#2c7675',
    },
    status: 40,
    subdomain: 'hope1312',
  },
  {
    id: 26,
    name: 'FAM Anchor Churches',
    settings: {
      meta_title: 'Live The Promise - Volunteer Coordination System',
      meta_desc: '',
      color_primary: '#95BA3D',
      color_secondary: '#5D482F',
      color_set_navbar: 'white-black',
      color_primary_text: '#fff',
      color_primary_contrast: 'offset',
      color_primary_offset: '#63880b',
      color_secondary_text: '#000',
      color_secondary_contrast: '',
      color_secondary_offset: '#8f7a61',
    },
    status: 40,
    subdomain: 'fam',
  },
  {
    id: 27,
    name: 'Restoration 225',
    settings: {
      meta_title: 'Restoration 225 - Volunteer Coordination System',
      meta_desc: '',
      color_primary: '#F6921E',
      color_secondary: '#1B75BB',
      color_set_navbar: 'white-black',
      color_primary_text: '#fff',
      color_primary_contrast: 'offset',
      color_primary_offset: '#c46000',
      color_secondary_text: '#000',
      color_secondary_contrast: '',
      color_secondary_offset: '#4da7ed',
    },
    status: 40,
    subdomain: 'restoration225',
  },
  {
    id: 28,
    name: 'CoMission',
    settings: {
      meta_title: 'CoMission - Volunteer Coordination System',
      meta_desc: '',
      color_primary: '#8F3423',
      color_secondary: '#847363',
      color_set_navbar: 'black-white',
      color_primary_text: '#000',
      color_primary_contrast: '',
      color_primary_offset: '#c16655',
      color_secondary_text: '#000',
      color_secondary_contrast: '',
      color_secondary_offset: '#b6a595',
    },
    status: 40,
    subdomain: 'comission',
  },
  {
    id: 29,
    name: 'Coalition of Care',
    settings: {
      meta_title: 'Coalition Care',
      meta_desc: 'Volunteer Coordination System for Coalition Care',
      color_primary: '#E23340',
      color_secondary: '#224289',
      color_set_navbar: 'white-black',
      color_primary_text: '#000',
      color_primary_contrast: '',
      color_primary_offset: '#ff6572',
      color_secondary_text: '#000',
      color_secondary_contrast: '',
      color_secondary_offset: '#5474bb',
    },
    status: 40,
    subdomain: 'coalitionofcare',
  },
  {
    id: 30,
    name: '4KIDS of Central Texas',
    settings: {
      meta_title: '4KIDS of Central Texas - Volunteer Coordination System',
      meta_desc: '',
      color_primary: '#1897DF',
      color_secondary: '#000000',
      color_set_navbar: 'white-black',
      color_primary_text: '#fff',
      color_primary_contrast: 'offset',
      color_primary_offset: '#0065ad',
      color_secondary_text: '#000',
      color_secondary_contrast: '',
      color_secondary_offset: '#323232',
    },
    status: 40,
    subdomain: '4kidsctx',
  },
  {
    id: 32,
    name: 'GoProject',
    settings: {
      meta_title: 'GoProject - Volunteer Coordination System',
      meta_desc: '',
      color_primary: '#000000',
      color_secondary: '#F56600',
      color_set_navbar: 'white-black',
      color_primary_text: '#000',
      color_primary_contrast: '',
      color_primary_offset: '#323232',
      color_secondary_text: '#000',
      color_secondary_contrast: '',
      color_secondary_offset: '#ff9832',
    },
    status: 40,
    subdomain: 'goproject',
  },
  {
    id: 33,
    name: 'New Oaks Community',
    settings: {
      meta_title: 'New Oaks Community - Promise Serves',
      meta_desc: 'www.newoakscommunity.org',
      color_primary: '#81BBC9',
      color_secondary: '#232524',
      color_set_navbar: 'white-black',
      color_primary_text: '#fff',
      color_primary_contrast: 'offset',
      color_primary_offset: '#4f8997',
      color_secondary_text: '#000',
      color_secondary_contrast: '',
      color_secondary_offset: '#555756',
    },
    status: 40,
    subdomain: 'tfh',
  },
  {
    id: 34,
    name: 'Fostering Family Ministries',
    settings: {
      meta_title: 'Fostering Family Ministries - Volunteer Coordination System',
      meta_desc: '',
      color_primary: '#0663A6',
      color_secondary: '#F9AB25',
      color_set_navbar: 'black-white',
      color_primary_text: '#000',
      color_primary_contrast: '',
      color_primary_offset: '#3895d8',
      color_secondary_text: '#fff',
      color_secondary_contrast: 'offset',
      color_secondary_offset: '#c77900',
    },
    status: 40,
    subdomain: 'ffm',
  },
  {
    id: 35,
    name: 'Belong + Bloom',
    settings: {
      meta_title: 'The Bloom House - Volunteer Coordination System',
      meta_desc: '',
      color_primary: '#81B063',
      color_secondary: '#DDDDDD',
      color_set_navbar: 'white-black',
      color_primary_text: '#fff',
      color_primary_contrast: 'offset',
      color_primary_offset: '#4f7e31',
      color_secondary_text: '#fff',
      color_secondary_contrast: 'offset',
      color_secondary_offset: '#ababab',
    },
    status: 40,
    subdomain: 'bloom',
  },
  {
    id: 36,
    name: 'Dwell Orphan Care',
    settings: {
      meta_title: 'Promise Serves - Dwell Orphan Care Volunteer Management',
      meta_desc: '',
      color_primary: '#005977',
      color_secondary: '#919191',
      color_set_navbar: 'white-black',
      color_primary_text: '#000',
      color_primary_contrast: '',
      color_primary_offset: '#328ba9',
      color_secondary_text: '#fff',
      color_secondary_contrast: 'offset',
      color_secondary_offset: '#5f5f5f',
    },
    status: 40,
    subdomain: 'dwell',
  },
  {
    id: 37,
    name: 'Project Belong',
    settings: {
      meta_title: 'Promise Serves - Project Belong Volunteer Coordination',
      meta_desc:
        'Inspiring, Recruiting and Resourcing the Church in Northern Virginia to care for vulnerable children with the love of Jesus.',
      color_primary: '#0E71B0',
      color_secondary: '#E8C322',
      color_set_navbar: 'white-black',
      color_primary_text: '#000',
      color_primary_contrast: '',
      color_primary_offset: '#40a3e2',
      color_secondary_text: '#fff',
      color_secondary_contrast: 'offset',
      color_secondary_offset: '#b69100',
    },
    status: 40,
    subdomain: 'projectbelong',
  },
  {
    id: 38,
    name: 'Nebraska 117',
    settings: {
      meta_title: 'Promise Serves - Project Belong Volunteer Coordination',
      meta_desc: '',
      color_primary: '#ABAC22',
      color_secondary: '#1F1D18',
      color_set_navbar: 'white-black',
      color_primary_text: '#fff',
      color_primary_contrast: 'offset',
      color_primary_offset: '#797a00',
      color_secondary_text: '#000',
      color_secondary_contrast: '',
      color_secondary_offset: '#514f4a',
    },
    status: 40,
    subdomain: 'ne117',
  },
  {
    id: 39,
    name: 'Centre County Orphan Alliance',
    settings: {
      meta_title:
        'Centre Conty Orphan Alliance - Volunteer Coordination System',
      meta_desc: '',
      color_primary: '#F49D2E',
      color_secondary: '#5AA1CF',
      color_set_navbar: 'white-black',
      color_primary_text: '#fff',
      color_primary_contrast: 'offset',
      color_primary_offset: '#c26b00',
      color_secondary_text: '#fff',
      color_secondary_contrast: 'offset',
      color_secondary_offset: '#286f9d',
    },
    status: 40,
    subdomain: 'ccoca',
  },
  {
    id: 40,
    name: 'Ohio Ministry Network',
    settings: {
      meta_title: '',
      meta_desc: '',
      color_primary: '#007CBB',
      color_secondary: '#333333',
      color_set_navbar: 'white-black',
      color_primary_text: '#000',
      color_primary_contrast: '',
      color_primary_offset: '#32aeed',
      color_secondary_text: '#000',
      color_secondary_contrast: '',
      color_secondary_offset: '#656565',
    },
    status: 40,
    subdomain: 'omn',
  },
  {
    id: 42,
    name: 'The Advocate Mission',
    settings: {
      meta_title: '',
      meta_desc: '',
      color_primary: '#223516',
      color_secondary: '#4E8118',
      color_set_navbar: 'white-black',
      color_primary_text: '#000',
      color_primary_contrast: '',
      color_primary_offset: '#546748',
      color_secondary_text: '#000',
      color_secondary_contrast: '',
      color_secondary_offset: '#80b34a',
    },
    status: 40,
    subdomain: 'theadvocate',
  },
  {
    id: 43,
    name: 'South Texas Alliance for Orphans',
    settings: {
      meta_title:
        'South Texas Alliance for Orphans - Volunteer Coordination System',
      meta_desc: '',
      color_primary: '#5EBD85',
      color_secondary: '#7F6FAE',
      color_set_navbar: 'white-black',
      color_primary_text: '#fff',
      color_primary_contrast: 'offset',
      color_primary_offset: '#2c8b53',
      color_secondary_text: '#fff',
      color_secondary_contrast: 'offset',
      color_secondary_offset: '#4d3d7c',
    },
    status: 40,
    subdomain: 'stafo',
  },
  {
    id: 44,
    name: 'DC127',
    settings: {
      meta_title: 'DC127 - Volunteer Coordination System',
      meta_desc: '',
      color_primary: '#882077',
      color_secondary: '#3A8B8F',
      color_set_navbar: 'white-black',
      color_primary_text: '#000',
      color_primary_contrast: '',
      color_primary_offset: '#ba52a9',
      color_secondary_text: '#000',
      color_secondary_contrast: '',
      color_secondary_offset: '#6cbdc1',
    },
    status: 40,
    subdomain: 'dc127',
  },
  {
    id: 45,
    name: 'ema',
    settings: {
      meta_title: 'ema Advocate Portal',
      meta_desc: '',
      color_primary: '#212E52',
      color_secondary: '#000000',
      color_set_navbar: 'white-black',
      color_primary_text: '#000',
      color_primary_contrast: '',
      color_primary_offset: '#536084',
      color_secondary_text: '#000',
      color_secondary_contrast: '',
      color_secondary_offset: '#323232',
    },
    status: 40,
    subdomain: 'ema',
  },
]
