<template>
  <section class="p-8">
    <div class="flex flex-col">
      <a v-for="url in urls" :key="url" :href="url" target="_new">{{ url }}</a>
    </div>

    <dl v-if="false">
      <dt>
        <a
          href="http://designcoder.test/demo/"
          data-date-added="1607735171"
        >promise-lab.test
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/#"
          data-date-added="1607839117"
        >
          designcoder.test/demo/#
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/about"
          data-date-added="1607782996"
        >
          designcoder.test/demo/about
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/advocates"
          data-date-added="1607783037"
        >
          designcoder.test/demo/advocates
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/affiliates"
          data-date-added="1607783059"
        >
          designcoder.test/demo/affiliates
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/agencies"
          data-date-added="1607783086"
        >
          designcoder.test/demo/agencies
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/aspect-ratio"
          data-date-added="1607783117"
        >
          designcoder.test/demo/aspect-ratio
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/avatars"
          data-date-added="1607853777"
        >
          designcoder.test/demo/avatars
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/bounce"
          data-date-added="1607853826"
        >
          designcoder.test/demo/bounce
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/breadcrumb"
          data-date-added="1607853886"
        >
          designcoder.test/demo/breadcrumb
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/calendar"
          data-date-added="1607782969"
        >
          designcoder.test/demo/calendar
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/care-requests"
          data-date-added="1607783229"
        >
          designcoder.test/demo/care-requests
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/cases"
          data-date-added="1607783684"
        >
          designcoder.test/demo/cases
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/churches"
          data-date-added="1607854697"
        >
          designcoder.test/demo/churches
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/communities"
          data-date-added="1607783394"
        >
          designcoder.test/demo/communities
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/compose-message"
          data-date-added="1607855351"
        >
          designcoder.test/demo/compose-message
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/contact-cards"
          data-date-added="1607855388"
        >
          designcoder.test/demo/contact-cards
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/contact-us"
          data-date-added="1607838936"
        >
          designcoder.test/demo/contact-us
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/content-placeholder"
          data-date-added="1607989873"
        >
          designcoder.test/demo/content-placeholder
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/countdown-clock"
          data-date-added="1607856350"
        >
          designcoder.test/demo/countdown-clock
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/css-grid"
          data-date-added="1607856261"
        >
          designcoder.test/demo/css-grid
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/customers"
          data-date-added="1609435346"
        >
          designcoder.test/demo/customers
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/dashboard"
          data-date-added="1609435444"
        >
          designcoder.test/demo/dashboard
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/datatables"
          data-date-added="1607782922"
        >
          designcoder.test/demo/datatables
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/dropdown"
          data-date-added="1607856047"
        >
          designcoder.test/demo/dropdown
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/dropdowns"
          data-date-added="1607856005"
        >
          designcoder.test/demo/dropdowns
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/easier-transitions#"
          data-date-added="1607855969"
        >
          designcoder.test/demo/easier-transitions
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/ema"
          data-date-added="1607989948"
        >
          designcoder.test/demo/ema
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/episodes"
          data-date-added="1609445891"
        >
          designcoder.test/demo/episodes
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/events"
          data-date-added="1607783254"
        >
          designcoder.test/demo/events
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/fam"
          data-date-added="1607856768"
        >
          designcoder.test/demo/fam
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/families"
          data-date-added="1607783418"
        >
          designcoder.test/demo/families
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/faq"
          data-date-added="1607856712"
        >
          designcoder.test/demo/faq
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/fetch"
          data-date-added="1607856637"
        >
          designcoder.test/demo/fetch
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/full-width-with-sidebar"
          data-date-added="1607838995"
        >
          designcoder.test/demo/full-width-with-sidebar
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/gratitude"
          data-date-added="1607856868"
        >
          designcoder.test/demo/gratitude
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/guidelines"
          data-date-added="1607864337"
        >
          designcoder.test/demo/guidelines
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/hero"
          data-date-added="1607836363"
        >
          designcoder.test/demo/hero
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/icons"
          data-date-added="1607877606"
        >
          designcoder.test/demo/icons
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/image-selection"
          data-date-added="1607875645"
        >
          designcoder.test/demo/image-selection
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/image-slider"
          data-date-added="1607875389"
        >
          designcoder.test/demo/image-slider
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/import"
          data-date-added="1607875356"
        >
          designcoder.test/demo/import
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/lab"
          data-date-added="1607833671"
        >
          designcoder.test/demo/lab
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/limiters"
          data-date-added="1607874710"
        >
          designcoder.test/demo/limiters
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/links"
          data-date-added="1607989690"
        >
          designcoder.test/demo/links
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/login"
          data-date-added="1607868840"
        >
          designcoder.test/demo/login
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/logos"
          data-date-added="1607868441"
        >
          designcoder.test/demo/logos
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/map-report"
          data-date-added="1607868417"
        >
          designcoder.test/demo/map-report
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/modal-dialog"
          data-date-added="1607856104"
        >
          designcoder.test/demo/modal-dialog
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/my-profile"
          data-date-added="1607874179"
        >
          designcoder.test/demo/my-profile
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/my-volunteer-requests"
          data-date-added="1607868790"
        >
          designcoder.test/demo/my-volunteer-requests
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/notifications"
          data-date-added="1607867993"
        >
          designcoder.test/demo/notifications
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/organizations"
          data-date-added="1607879743"
        >
          designcoder.test/demo/organizations
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/organizations/ema"
          data-date-added="1607881183"
        >
          designcoder.test/demo/organizations/ema
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/placeholders"
          data-date-added="1607867673"
        >
          designcoder.test/demo/placeholders
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/podcasts"
          data-date-added="1609435245"
        >
          designcoder.test/demo/podcasts
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/posts"
          data-date-added="1609435198"
        >
          designcoder.test/demo/posts
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/preferences"
          data-date-added="1607783620"
        >
          designcoder.test/demo/preferences
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/profile"
          data-date-added="1607783202"
        >
          designcoder.test/demo/profile
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/public-dashboard"
          data-date-added="1607836321"
        >
          designcoder.test/demo/public-dashboard
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/recent-posts"
          data-date-added="1607838912"
        >
          designcoder.test/demo/recent-posts
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/regions"
          data-date-added="1607866565"
        >
          designcoder.test/demo/regions
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/reports"
          data-date-added="1607839065"
        >
          designcoder.test/demo/reports
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/reports"
          data-date-added="1607783503"
        >
          designcoder.test/demo/reports
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/resources"
          data-date-added="1607783148"
        >
          designcoder.test/demo/resources
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/resumes/1"
          data-date-added="1608375138"
        >
          designcoder.test/demo/resumes/1
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/requests"
          data-date-added="1607783172"
        >
          designcoder.test/demo/requests
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/row-actions"
          data-date-added="1607839039"
        >
          designcoder.test/demo/row-actions
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/scroll-detection"
          data-date-added="1607865819"
        >
          designcoder.test/demo/scroll-detection
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/sidebar"
          data-date-added="1607865587"
        >
          designcoder.test/demo/sidebar
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/signin"
          data-date-added="1607865535"
        >
          designcoder.test/demo/signin
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/simple-cards"
          data-date-added="1607865329"
        >
          designcoder.test/demo/simple-cards
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/slack-clone"
          data-date-added="1607864910"
        >
          designcoder.test/demo/slack-clone
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/staff"
          data-date-added="1607864649"
        >
          designcoder.test/demo/staff
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/setting"
          data-date-added="1607875317"
        >
          designcoder.test/demo/setting
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/settings"
          data-date-added="1607783641"
        >
          designcoder.test/demo/settings
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/steps"
          data-date-added="1607864421"
        >
          designcoder.test/demo/steps
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/stories"
          data-date-added="1607864398"
        >
          designcoder.test/demo/stories
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/uses"
          data-date-added="1607863533"
        >
          designcoder.test/demo/uses
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/tabs"
          data-date-added="1607864180"
        >
          designcoder.test/demo/tabs
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/tagify"
          data-date-added="1607864150"
        >
          designcoder.test/demo/tagify
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/team"
          data-date-added="1607989638"
        >
          designcoder.test/demo/team
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/terms"
          data-date-added="1607864108"
        >
          designcoder.test/demo/terms
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/testing"
          data-date-added="1607864084"
        >
          designcoder.test/demo/testing
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/timeline"
          data-date-added="1607864040"
        >
          designcoder.test/demo/timeline
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/todo-app-and-x-model"
          data-date-added="1607864010"
        >
          designcoder.test/demo/todo-app-and-x-model
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/transitions-delay"
          data-date-added="1607863903"
        >
          designcoder.test/demo/transitions-delay
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/transitions-duration"
          data-date-added="1607863775"
        >
          designcoder.test/demo/transitions-duration
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/transitions-dropdown"
          data-date-added="1607863659"
        >
          designcoder.test/demo/transitions-dropdown
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/transitions-modal"
          data-date-added="1607863620"
        >
          designcoder.test/demo/transitions-modal
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/transitions-property"
          data-date-added="1607863708"
        >
          designcoder.test/demo/transitions-property
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/transitions-sidebar"
          data-date-added="1607863567"
        >
          designcoder.test/demo/transitions-sidebar
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/transitions-timing-function"
          data-date-added="1607863962"
        >
          designcoder.test/demo/transitions-timing-function
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/user/login"
          data-date-added="1609435396"
        >
          designcoder.test/demo/user/login
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/volunteer-actions"
          data-date-added="1607863491"
        >
          designcoder.test/demo/volunteer-actions
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/volunteer-limiters"
          data-date-added="1607863468"
        >
          designcoder.test/demo/volunteer-limiters
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/volunteers"
          data-date-added="1607783437"
        >
          designcoder.test/demo/volunteers
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/welcome"
          data-date-added="1607863420"
        >
          designcoder.test/demo/welcome
        </a>
      </dt>
      <dt>
        <a
          href="http://designcoder.test/demo/work-request-form"
          data-date-added="1607863352"
        >
          designcoder.test/demo/work-request-form
        </a>
      </dt>
    </dl>
  </section>
</template>
<script>
const pages = [
  '100',
  '99',
  'a11y',
  'abilities',
  'about',
  'about-us',
  'accordion-toggle-and-loops',
  'accounts',
  'activities',
  'add-another',
  'add-assignment',
  'add-need',
  'adoption-101',
  'ads',
  'advanced-search',
  'advocate',
  'advocate-dashboard',
  'advocate-quick-add',
  'advocates',
  'affiliates',
  'affiliates-nav-menu',
  'affiliates-select-input',
  'affordances',
  'agencies',
  'albums',
  'alerts',
  'alumni',
  'animations-bounce',
  'animations-ping',
  'animations-pulse',
  'animations-spin',
  'animations-wiggle',
  'api',
  'apis',
  'apply',
  'apps',
  'articles',
  'aspect-ratio',
  'assets',
  'associates',
  'atoms',
  'attributes',
  'auth',
  'avatars',
  'backend',
  'background-color',
  'badge',
  'badges',
  'banners',
  'bedroom',
  'benefits',
  'best-practices',
  'blog',
  'blog-section',
  'body-styles',
  'bookmarks',
  'books',
  'bootstrap',
  'brand',
  'brand-team',
  'brands',
  'breadcrumb',
  'breadcrumbs',
  'bullet-journal',
  'button',
  'button-groups',
  'buttons',
  'buy',
  'buyers',
  'calendar',
  'calendar-add-event',
  'campaigns',
  'card',
  'care',
  'care-communities',
  'care-portal',
  'care-requests',
  'careers',
  'carousel',
  'cars',
  'cases',
  'categories',
  'celebration',
  'center',
  'centers',
  'certificate',
  'change',
  'changelog',
  'cheatsheat',
  'cheatsheets',
  'checklists',
  'church',
  'church-actions',
  'church-volunteer-requests',
  'churches',
  'churches-select-input',
  'classrooms',
  'clients',
  'code',
  'collaborators',
  'color',
  'colors',
  'comment-threads',
  'communities',
  'communities-limiters',
  'communities-select-input',
  'community-actions',
  'companies',
  'compare',
  'component-status',
  'components',
  'compose-message',
  'composition-api',
  'conferences',
  'contact',
  'contact-cards',
  'contact-info',
  'contact-us',
  'contacts',
  'containers',
  'content-placeholder',
  'contexts',
  'contractors',
  'countdown-clock',
  'countries',
  'courage',
  'course',
  'courses',
  'create',
  'credit-card-fields',
  'credits',
  'cruddy-by-design',
  'css-grid',
  'css-only-dropdown',
  'cssgrid',
  'cta-section',
  'custom-properties',
  'cypress',
  'dashboard',
  'dashboards',
  'data',
  'data-import-select-input',
  'data-table',
  'data-visualization',
  'datatables',
  'date-input',
  'date-picker',
  'dayparts',
  'dealers',
  'debug',
  'delete',
  'design-system',
  'design-systems',
  'design-tokens',
  'designers',
  'destination',
  'destroy',
  'developers',
  'diagrams',
  'directory',
  'divide',
  'docs',
  'documentation',
  'domain-knowledge',
  'domains',
  'donate',
  'donors',
  'dropdown',
  'dropdowns',
  'drupal',
  'easier-transitions',
  'edit',
  'education',
  'elements',
  'ema',
  'email',
  'emailer',
  'entrepreneurs',
  'entrepreneurship',
  'episodes',
  'essentials',
  'event-limiters',
  'events',
  'experience',
  'fading-background',
  'fam',
  'fam-form',
  'families',
  'family-actions',
  'faq',
  'faqs',
  'features',
  'feeds',
  'fetch',
  'filepond',
  'find',
  'flexbox',
  'flows',
  'flyout-menu',
  'focus',
  'fonts',
  'form',
  'frontend',
  'full-width-with-sidebar',
  'gallery',
  'georgia-seow',
  'get-involved',
  'git',
  'give',
  'giving',
  'glossary',
  'google-analytics',
  'gradients',
  'gratitude',
  'grid',
  'grid-layout',
  'grid-on-brand',
  'grid-with-offset-icons',
  'grit',
  'groups',
  'guidelines',
  'habits',
  'headers',
  'headlines',
  'hear',
  'help',
  'help-or-feedback-request-form',
  'hero',
  'hero-card',
  'heros',
  'history',
  'home',
  'i18n',
  'icon',
  'icons',
  'illustrations',
  'image',
  'image-selection',
  'image-slider',
  'images',
  'impact',
  'import',
  'index',
  'ingredients',
  'input',
  'input-groups',
  'integrations',
  'intranets',
  'invoices',
  'jamstack',
  'javascript',
  'keyboard-shortcuts',
  'kirby',
  'lab',
  'languages',
  'layouts',
  'leaderboard',
  'lesson',
  'lessons',
  'license',
  'licenses',
  'limiters',
  'line-height',
  'link',
  'links',
  'list-search-page-heading',
  'listen',
  'listening',
  'log',
  'login',
  'logo-cloud',
  'logos',
  'logs',
  'makes',
  'manager',
  'map-report',
  'markets',
  'media',
  'media-objects',
  'members',
  'messages',
  'methods',
  'mocks',
  'modal',
  'modal-dialog',
  'modals',
  'models',
  'modules',
  'molecules',
  'moms',
  'movies',
  'muuri-grid',
  'my-profile',
  'my-profile-menu',
  'my-volunteer-requests',
  'navbar',
  'navbar-profile-notifications-menu',
  'navbar-with-breadcrumb',
  'navbars',
  'needs',
  'news',
  'next',
  'nomenclature',
  'notes',
  'notices',
  'notifications',
  'now',
  'oauth_callback',
  'object-fit',
  'old-welcome',
  'order',
  'orders',
  'organisms',
  'overlap',
  'overview',
  'owners',
  'packages',
  'page-heading',
  'page-headings',
  'pages',
  'panels',
  'partners',
  'patterns',
  'people',
  'permissions',
  'personas',
  'photos',
  'php',
  'physicians',
  'pitches',
  'pivot-tables',
  'placeholders',
  'plan-and-billing',
  'podcast_episodes',
  'podcasts',
  'popover',
  'portfolio',
  'post-types',
  'posters',
  'posts',
  'preferences',
  'prices',
  'pricing',
  'principles',
  'privacy',
  'prizes',
  'process',
  'product-management',
  'products',
  'profile',
  'profile-dropdown',
  'programs',
  'progress',
  'progress-bar',
  'progress-indicator',
  'projects',
  'projects-list',
  'promise_serves',
  'properties',
  'prospects',
  'public',
  'public-dashboard',
  'python',
  'quotes',
  'radio-group-input',
  'ratings-input',
  'react',
  'reading',
  'recent-posts',
  'recipes',
  'reduce-motion',
  'regions',
  'releases',
  'remove',
  'reporting',
  'reports',
  'reports-select-input',
  'requests',
  'resources',
  'responsive-css-grid',
  'responsive-flex-box',
  'rest',
  'resume',
  'resumes',
  'reviews',
  'role-select-input',
  'roles',
  'roles_select',
  'row-actions-dropdown',
  'ruby',
  'samples',
  'save',
  'schema',
  'scratch',
  'screencasts',
  'screens',
  'scroll-detection',
  'search',
  'sections',
  'security',
  'see',
  'select-input',
  'select-menus',
  'sellers',
  'selling',
  'sentry',
  'services',
  'setting',
  'settings',
  'settings-screen',
  'ship',
  'show',
  'side-projects',
  'sidebar',
  'signin',
  'signup',
  'simple-footer',
  'sites',
  'situations',
  'skills',
  'slack-clone',
  'slide-overs',
  'snippets',
  'social',
  'solutions',
  'songs',
  'specials',
  'specimen',
  'spf-overview',
  'split',
  'sponsor',
  'sponsors',
  'stack',
  'staff',
  'staff-actions-dropdown',
  'staff-dashboard',
  'standards',
  'stat',
  'statamic',
  'state-management',
  'states',
  'stats',
  'status',
  'steps',
  'sticky',
  'store',
  'stories',
  'storybook',
  'stubs',
  'students',
  'subscribe',
  'subscription',
  'subscriptions',
  'svelte',
  'syllabus',
  'tables',
  'tabs',
  'tagify',
  'tags',
  'tasks',
  'team',
  'tech',
  'technical-assistance',
  'technical-support',
  'technologies',
  'templates',
  'terms',
  'testimonial-card',
  'testimonial-with-overlapping-image',
  'testing',
  'textarea',
  'thanks',
  'timeline',
  'tips',
  'todo-app-and-x-model',
  'topics',
  'track',
  'training',
  'transitions-delay',
  'transitions-dropdown',
  'transitions-duration',
  'transitions-modal',
  'transitions-property',
  'transitions-sidebar',
  'transitions-timing-function',
  'trending',
  'trends',
  'tricks',
  'tutorials',
  'types',
  'typescript',
  'typography',
  'ui',
  'upcoming',
  'update',
  'upload',
  'uploads',
  'user-profile-slideover',
  'uses',
  'ux',
  'vectors',
  'vehicles',
  'videos',
  'visit',
  'volunteer',
  'volunteer-actions',
  'volunteer-limiters',
  'volunteers',
  'vue',
  'watch',
  'watching',
  'webinars',
  'welcome',
  'wisdom',
  'wordpress',
  'work-request',
  'work-samples',
  'workflow',
  'workshops',
  'zones',
  'css-grid-layout',
  'fixed',
  'manage_pro',
  'quick-links-dropdown',
  'simple-cards',
  'work-request-form',
]
export default {
  data() {
    return {
      baseUrl: 'http://designcoder.test',
      pages,
    }
  },
  computed: {
    urls() {
      return this.pages.map(page => `${this.baseUrl}/demo/${page}`)
    },
  },
}
</script>
